### ISSUE TITLE
Logging Application Errors and Debugmessages

### ISSUE THREAD

**Issue by ayeks** [ohaz/amos-ss15-proj1#39]
Do we want to introduce a logging system into our framework? With the rising complexity and functionality it would be great if i can run the server in debugmode to get as many information as possible. 
Additionally we could generate error mails when an exception occures at the productive system.

Flask Logging: http://flask.pocoo.org/docs/0.10/errorhandling/
Simple Flask Log Example: https://gist.github.com/ibeex/3257877

Is it possible to use the FileLogger in the cloud environment if we need to? Or is it to costly or forbidden to generate files for some reason?

**Comment by MacBlub** [comment]
Hmm, well Logging seems to be a very good idea. 
As far as I know, google supports logging with several logging types, which can be filtered in the logging-concole in the cloud.[sever, debug and so on] 

Flask uses this interface too, but we can't use RotatingFileHandler, etc. because they are logging to the local fileysystem, which is forbidden.

But I've seen on the google-page locations, where logs may be written, too.[not verified] There seems to be stub usable for the regular LOG-Viewer, and we even can pipe the log directly in the storage [system-account?]

Maybe for every cloud, we can use diffrent logger-outputs? Cloud A to the storage, Cloud B to the Viewer, etc? Like the Storage-Interface?

Generating Mails only seems useful, if the app is already in use, not so much in the development-process.

**Comment by ohaz** [comment]
+1 for this idea

**Comment by paswa** [comment]
Just to add my 2 cent on this: we've got a working storage interface in every cloud, right? Would it be possible to pipe the log through that interface and thereby save it in the cloud? Obviously this won't work if the storage interface itself is broken, though.

**Comment by ohaz** [comment]
Done
