### ISSUE TITLE
Save File Dialog wont fade out on click on "Save result"

### ISSUE THREAD

**Issue by ayeks** [ohaz/amos-ss15-proj1#53]
When saving a file, in the dialog, a click on "Save result" should result in a fadout of the dialog. Like the fade out when clicking on "Close".

I think it worked in the past that way, our functional tests are expecting this behaviour.
Functional tests "index-file-management" and "userauth" are currently disabled because of this bug.

**Comment by MacBlub** [comment]
The Bug was mainly in views.py, 
Synchronization for saving files was nearly successful, but .get waited on the wrong queue, and so caused a timeout. This lead to an Exception, which lead to 500 response in the calculator. So the behaviour in the calculator was correct, but the behaviour of the app not.
Should be fixed in this commit: 
* SHA: 8aa6ca5fee5ff1dcced4374dbda3ab7f06e474f9

**Comment by ayeks** [comment]
Userinterface waits for response from all cloud servers. The popup fades out when a HTTP response is returned. Because of issue #51 that response isnt returned sometimes.
